services:
  db:
    image: postgres:15-alpine
    container_name: db-adoptions
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net-adopt

  nextjs_app:
    build: ./adoptions-app
    container_name: app-adopt-nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - net-adopt
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: app-adopt-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - net-adopt
    depends_on:
      - nextjs_app
